"""PHIL parameter lookup skill: on-demand parameter documentation for any DIALS command."""

import os
from pathlib import Path

from .base import BaseSkill, SkillContext

TOOLS: list[dict] = [
    {
        "name": "lookup_phil_params",
        "description": "Look up the full PHIL parameter documentation for any DIALS command. Returns the complete parameter listing with help text, types, defaults, and expert levels. Use this when the user asks about available parameters for a specific command, wants to know what options exist, or when you need to suggest advanced parameters for troubleshooting. This reads from pre-fetched documentation generated by running 'dials.program -c -e2 -a2'.",
        "input_schema": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string",
                    "description": "The DIALS command name (e.g., 'dials.index', 'dials.scale', 'dials.find_spots')"
                },
                "search_term": {
                    "type": "string",
                    "description": "Optional: search for a specific parameter or keyword within the output (case-insensitive). If provided, only matching lines and their context will be returned."
                }
            },
            "required": ["command"]
        }
    },
]

# Directories to search for command documentation, in priority order
_DOCS_ROOT = Path(__file__).parent.parent.parent / "docs"
_PHIL_PARAMS_DIR = _DOCS_ROOT / "phil_params"   # machine-generated PHIL dumps
_PROGRAMS_DIR = _DOCS_ROOT / "programs"          # human-readable markdown docs


def lookup_phil_params(command: str, search_term: str = "") -> str:
    """
    Look up documentation for a DIALS command.

    Checks (in order):
      1. docs/phil_params/<command>.txt  — machine-generated PHIL dump
      2. docs/programs/<command>.md      — human-readable markdown

    Args:
        command: DIALS command name (e.g., 'dials.index')
        search_term: Optional keyword to filter results
    """
    txt_name = command.replace(".", "_") + ".txt"
    filepath = _PHIL_PARAMS_DIR / txt_name
    if not filepath.exists():
        alt = Path(os.environ.get("DIALS_AGENT_ROOT", "")) / "docs" / "phil_params" / txt_name
        if alt.exists():
            filepath = alt
        else:
            filepath = None

    if filepath is None:
        md_name = command.replace(".", "_") + ".md"
        md_path = _PROGRAMS_DIR / md_name
        if md_path.exists():
            filepath = md_path

    if filepath is None:
        return (
            f"No documentation found for '{command}'.\n"
            f"Checked: {_PHIL_PARAMS_DIR / txt_name}\n"
            f"         {_PROGRAMS_DIR / (command.replace('.', '_') + '.md')}\n"
            f"Generate PHIL dump with: {command} -c -e2 -a2"
        )

    try:
        content = filepath.read_text(encoding="utf-8")
    except Exception as e:
        return f"Error reading PHIL params for {command}: {e}"

    if not search_term:
        if len(content) > 15000:
            return (
                content[:15000] +
                f"\n\n... [TRUNCATED - {len(content)} chars total. "
                f"Use search_term to find specific parameters]"
            )
        return content

    search_lower = search_term.lower()
    lines = content.split("\n")
    matching_sections = []

    for i, line in enumerate(lines):
        if search_lower in line.lower():
            start = max(0, i - 2)
            end = min(len(lines), i + 6)
            section = "\n".join(lines[start:end])
            matching_sections.append(f"--- Line {i+1} ---\n{section}")

    if not matching_sections:
        return f"No parameters matching '{search_term}' found in {command}."

    return (
        f"Parameters matching '{search_term}' in {command}:\n\n" +
        "\n\n".join(matching_sections)
    )


class PhilParamsSkill(BaseSkill):

    @property
    def name(self) -> str:
        return "phil_params"

    @property
    def description(self) -> str:
        return "On-demand PHIL parameter documentation lookup for all DIALS commands"

    def get_prompt_fragment(self) -> str:
        return """## PHIL Parameter Lookup

You have access to the **complete PHIL parameter documentation** for all 82 DIALS commands. When a user asks about available parameters, advanced options, or you need to find a specific parameter for troubleshooting:

1. Use the `lookup_phil_params` tool with the command name to get the full parameter listing
2. Use the `search_term` parameter to search for specific keywords within the output
3. The documentation includes help text, types, defaults, and expert levels

Example: To find all absorption-related parameters in dials.scale:
```
lookup_phil_params(command="dials.scale", search_term="absorption")
```

**IMPORTANT**: When users ask "what parameters does dials.X have?" or "what options are available for dials.X?", use the `lookup_phil_params` tool to give them accurate, complete information rather than relying on your memory alone."""

    def get_tools(self) -> list[dict]:
        return TOOLS

    def handle_tool_call(self, tool_name: str, tool_input: dict, context: SkillContext) -> dict:
        if tool_name != "lookup_phil_params":
            raise KeyError(f"phil_params skill does not handle tool '{tool_name}'")
        command = tool_input.get("command", "")
        search_term = tool_input.get("search_term", "")
        return {"phil_params": lookup_phil_params(command, search_term)}
